### ISSUE TITLE
Stuck when trying to send response back to message Bus

### ISSUE THREAD

**Issue by hanneslehmann** [asaskevich/EventBus#25] opened 2017-06-19 13:53 UTC
Hi,
I have modified the example and wanted to send the response of the calculator back on the bus, on a different topic. I would like to chain different functions to react on events down a chain. When I run "go run" process is stuck, nothing happens.

```go
package main
import (
    "fmt"
    "github.com/asaskevich/EventBus"
    "time"
)

var (
    bus  EventBus.Bus;
)

func calculator1(a int, b int) {
    fmt.Printf("calc1: %d\n", a + b)
    bus.Publish("print", "calc1 calculated : %d\n", a + b)
}

func printer(s string) {
	fmt.Println(s)
}

func main() {
	bus = EventBus.New();
    bus.Subscribe("calc", calculator1);
	bus.Subscribe("print", printer);
	sum := 1
    for sum < 10 {
        fmt.Println(sum)
        bus.Publish("calc", sum, sum);
        time.Sleep(1000 * time.Millisecond)
        sum += 1
    }
    bus.Unsubscribe("calc", calculator1);
    bus.Unsubscribe("print", printer);
}
```
Output
```bash
> go run poc3.go
1
calc1: 2
^Csignal: interrupt

```

I am on linux 64 bit.

**Comment by stackus** [comment] 2017-08-25 13:41
Happened upon this issue while evaluating the library for some work. Firing off new events from functions called from other events is something we'll need so I tried your example locally to see if I could get it to work.

Two changes are needed to make this work for me (macOS Sierra).
1. Use `fmt.Sprintf` on the arguments `"calc1 calculated : %d\n", a+b`. `printer` is only expecting a single parameter.
2. Use `SubscribeAsync` for the subscription to `calc` events. Transactional parameter can be either true or false.

**Comment by bennAH** [comment] 2018-01-03 00:12
@hanneslehmann Closing this issue. The problem is you have a subscribed synchronously therefore the callback has to complete first before the process can continue. The issue is the first call back never completes. @stackus 2nd suggestion is correct that you should SubscribeAsync if you want this behaviour.

**Closed by bennAH** 2018-01-03 00:12 UTC
